export interface CommandMetadata {
  id: string;
  names: string[];
  category: string;
  usage: string;
  description: string;
  hidden?: boolean;
}

export const COMMAND_CATEGORY_TITLES: Record<string, string> = {
  explore: '移動與探索',
  character: '角色資訊',
  item: '物品操作',
  combat: '戰鬥指令',
  mount: '坐騎',
  social: '社交',
  quest: '任務系統',
  dungeon: '副本與競技',
  craft: '製作系統',
  guardian: '守護靈',
  kingdom: '王國系統',
  build: '建設系統',
  war: '軍事系統',
  treasury: '國庫系統',
  auction: '拍賣系統',
  fish: '釣魚系統',
  diplomacy: '外交系統',
  achievement: '成就/稱號/圖鑑',
  pet: '寵物系統',
  event: '世界事件',
  auto: '自動戰鬥',
  other: '其他',
};

export const COMMAND_METADATA: CommandMetadata[] = [
  { id: 'look', names: ['look'], category: 'explore', usage: 'look [目標]', description: '查看周圍環境、NPC、怪物或玩家' },
  { id: 'search', names: ['search'], category: 'explore', usage: 'search [目標]', description: '搜尋房間線索' },
  { id: 'inspect', names: ['inspect'], category: 'explore', usage: 'inspect <目標>', description: '檢查物件、出口或生物' },
  { id: 'open', names: ['open'], category: 'explore', usage: 'open <目標>', description: '開啟出口或寶箱' },
  { id: 'go', names: ['go', 'move'], category: 'explore', usage: 'go <方向>', description: '往 north/east/south/west 移動' },
  { id: 'map', names: ['map'], category: 'explore', usage: 'map', description: '顯示地圖' },
  { id: 'activate', names: ['activate'], category: 'explore', usage: 'activate portal', description: '啟用目前區域傳送陣' },
  { id: 'portals', names: ['portals'], category: 'explore', usage: 'portals', description: '查看傳送點解鎖狀態' },
  { id: 'travel', names: ['travel'], category: 'explore', usage: 'travel <傳送點>', description: '傳送到已啟用區域' },
  { id: 'recall', names: ['recall'], category: 'explore', usage: 'recall', description: '回到新手村廣場' },
  { id: 'rest', names: ['rest'], category: 'explore', usage: 'rest', description: '原地休息，恢復 HP 與資源' },
  { id: 'status', names: ['status'], category: 'character', usage: 'status', description: '查看角色狀態' },
  { id: 'faith', names: ['faith'], category: 'character', usage: 'faith', description: '查看信仰、祈禱與改信' },
  { id: 'pray', names: ['pray'], category: 'character', usage: 'pray', description: '祈禱提高恩寵' },
  { id: 'offering', names: ['offering'], category: 'character', usage: 'offering <數量>', description: '獻金提高恩寵' },
  { id: 'renounce', names: ['renounce'], category: 'character', usage: 'renounce', description: '放棄目前信仰' },
  { id: 'inventory', names: ['inventory'], category: 'character', usage: 'inventory', description: '查看背包' },
  { id: 'skills', names: ['skills'], category: 'character', usage: 'skills', description: '查看技能列表' },
  { id: 'allocate', names: ['allocate', 'alloc'], category: 'character', usage: 'allocate <屬性> <點>', description: '分配屬性點' },
  { id: 'equip', names: ['equip'], category: 'item', usage: 'equip <物品>', description: '裝備物品' },
  { id: 'unequip', names: ['unequip'], category: 'item', usage: 'unequip <物品>', description: '卸下裝備' },
  { id: 'use', names: ['use'], category: 'item', usage: 'use <物品>', description: '使用物品' },
  { id: 'take', names: ['take', 'pick', 'pickup', 'get'], category: 'item', usage: 'take <物品>', description: '拾取地上物品' },
  { id: 'loot', names: ['loot'], category: 'item', usage: 'loot [目標]', description: '拾取戰利品' },
  { id: 'drop', names: ['drop'], category: 'item', usage: 'drop <物品>', description: '丟棄物品' },
  { id: 'sell', names: ['sell'], category: 'item', usage: 'sell <物品> [數量]', description: '在商人旁出售背包物品' },
  { id: 'upgrade', names: ['upgrade', 'enhance'], category: 'item', usage: 'upgrade [裝備]', description: '強化裝備' },
  { id: 'reroll', names: ['reroll'], category: 'item', usage: 'reroll affix <instance> <序號>', description: '重骰裝備詞綴' },
  { id: 'lock', names: ['lock'], category: 'item', usage: 'lock affix <instance> <序號>', description: '鎖定裝備詞綴' },
  { id: 'reforge', names: ['reforge'], category: 'item', usage: 'reforge quality <instance>', description: '重鑄裝備品質' },
  { id: 'disassemble', names: ['disassemble'], category: 'item', usage: 'disassemble <物品>', description: '分解裝備取得重鑄材料' },
  { id: 'attack', names: ['attack'], category: 'combat', usage: 'attack <目標>', description: '近戰普攻' },
  { id: 'melee', names: ['melee'], category: 'combat', usage: 'melee <目標>', description: '切換近戰普攻' },
  { id: 'ranged', names: ['ranged', 'range'], category: 'combat', usage: 'ranged <目標>', description: '切換遠程/施法普攻' },
  { id: 'skill', names: ['skill'], category: 'combat', usage: 'skill <技能> [目標]', description: '使用技能' },
  { id: 'defend', names: ['defend'], category: 'combat', usage: 'defend', description: '防禦' },
  { id: 'escape', names: ['escape'], category: 'combat', usage: 'escape', description: '逃跑' },
  { id: 'charge', names: ['charge'], category: 'combat', usage: 'charge <目標>', description: '騎乘衝鋒' },
  { id: 'intercept', names: ['intercept'], category: 'combat', usage: 'intercept <方向>', description: '騎乘攔截' },
  { id: 'mounted', names: ['mounted'], category: 'combat', usage: 'mounted <動作>', description: '騎乘戰鬥動作' },
  { id: 'mount', names: ['mount'], category: 'mount', usage: 'mount [ride|dismount]', description: '查看或控制坐騎' },
  { id: 'say', names: ['say'], category: 'social', usage: 'say <訊息>', description: '說話' },
  { id: 'talk', names: ['talk'], category: 'social', usage: 'talk <NPC>', description: '與 NPC 對話' },
  { id: 'party', names: ['party'], category: 'social', usage: 'party <子指令>', description: '組隊系統' },
  { id: 'trade', names: ['trade'], category: 'social', usage: 'trade <子指令>', description: '交易系統' },
  { id: 'emote', names: ['emote'], category: 'social', usage: 'emote <動作>', description: '表情動作' },
  { id: 'friend', names: ['friend', 'friends'], category: 'social', usage: 'friend <子指令>', description: '好友系統' },
  { id: 'mail', names: ['mail'], category: 'social', usage: 'mail <子指令>', description: '郵件系統' },
  { id: 'weather', names: ['weather'], category: 'social', usage: 'weather', description: '查看天氣與時段' },
  { id: 'quest', names: ['quest'], category: 'quest', usage: 'quest <子指令>', description: '任務系統' },
  { id: 'classchange', names: ['classchange', 'job'], category: 'quest', usage: 'classchange <職業>', description: '轉職' },
  { id: 'classquest', names: ['classquest', 'cq'], category: 'quest', usage: 'classquest <子指令>', description: '職業任務' },
  { id: 'classquest2', names: ['classquest2', 'cq2'], category: 'quest', usage: 'classquest2 <子指令>', description: '進階職業任務' },
  { id: 'skilltree', names: ['skilltree', 'st'], category: 'quest', usage: 'skilltree <子指令>', description: '技能樹系統' },
  { id: 'enter', names: ['enter'], category: 'dungeon', usage: 'enter <入口>', description: '進入副本入口' },
  { id: 'dungeon', names: ['dungeon'], category: 'dungeon', usage: 'dungeon <子指令>', description: '副本系統' },
  { id: 'duel', names: ['duel'], category: 'dungeon', usage: 'duel <玩家>', description: 'PvP 決鬥' },
  { id: 'arena', names: ['arena'], category: 'dungeon', usage: 'arena', description: '競技場' },
  { id: 'leaderboard', names: ['leaderboard', 'rank'], category: 'dungeon', usage: 'leaderboard', description: '排行榜' },
  { id: 'craft', names: ['craft'], category: 'craft', usage: 'craft <配方|子指令>', description: '製作系統' },
  { id: 'gather', names: ['gather'], category: 'craft', usage: 'gather', description: '採集資源' },
  { id: 'ask', names: ['ask'], category: 'guardian', usage: 'ask', description: '向守護靈詢問建議' },
  { id: 'guardian', names: ['guardian'], category: 'guardian', usage: 'guardian <子指令>', description: '守護靈系統' },
  { id: 'kingdom', names: ['kingdom', 'k'], category: 'kingdom', usage: 'kingdom <子指令>', description: '王國系統' },
  { id: 'appoint', names: ['appoint'], category: 'kingdom', usage: 'appoint <玩家> <職位>', description: '任命王國成員' },
  { id: 'demote', names: ['demote'], category: 'kingdom', usage: 'demote <玩家>', description: '降職王國成員' },
  { id: 'kick', names: ['kick'], category: 'kingdom', usage: 'kick <玩家>', description: '踢出王國成員' },
  { id: 'guild', names: ['guild', 'g'], category: 'kingdom', usage: 'guild <子指令>', description: '公會系統' },
  { id: 'build', names: ['build'], category: 'build', usage: 'build <子指令>', description: '建設系統' },
  { id: 'mob', names: ['mob'], category: 'build', usage: 'mob <spawn|remove>', description: '管理怪物生成點' },
  { id: 'npc', names: ['npc'], category: 'build', usage: 'npc <place|remove|config>', description: '管理 NPC' },
  { id: 'war', names: ['war'], category: 'war', usage: 'war <子指令>', description: '戰爭系統' },
  { id: 'army', names: ['army'], category: 'war', usage: 'army <子指令>', description: '軍隊管理' },
  { id: 'bounty', names: ['bounty'], category: 'war', usage: 'bounty <子指令>', description: '懸賞系統' },
  { id: 'treasury', names: ['treasury'], category: 'treasury', usage: 'treasury <子指令>', description: '國庫系統' },
  { id: 'diplomacy', names: ['diplomacy'], category: 'diplomacy', usage: 'diplomacy <子指令>', description: '外交系統' },
  { id: 'shop', names: ['shop'], category: 'auction', usage: 'shop [NPC]', description: '開啟商店' },
  { id: 'buy', names: ['buy'], category: 'auction', usage: 'buy <物品>', description: '購買商店物品' },
  { id: 'auction', names: ['auction', 'ah'], category: 'auction', usage: 'auction <子指令>', description: '拍賣系統' },
  { id: 'market', names: ['market'], category: 'auction', usage: 'market <子指令>', description: '交易所系統' },
  { id: 'fish', names: ['fish'], category: 'fish', usage: 'fish [level]', description: '在水邊釣魚或查看釣魚等級' },
  { id: 'achievement', names: ['achievement', 'ach'], category: 'achievement', usage: 'achievement [equip]', description: '查看或裝備成就稱號' },
  { id: 'title', names: ['title'], category: 'achievement', usage: 'title', description: '查看當前稱號' },
  { id: 'codex', names: ['codex'], category: 'achievement', usage: 'codex <monster|fish|boss>', description: '查看圖鑑' },
  { id: 'appearance', names: ['appearance', 'cosmetic'], category: 'achievement', usage: 'appearance <子指令>', description: '外觀收藏' },
  { id: 'pet', names: ['pet'], category: 'pet', usage: 'pet <子指令>', description: '寵物系統' },
  { id: 'tame', names: ['tame'], category: 'pet', usage: 'tame', description: '馴服野生寵物' },
  { id: 'event', names: ['event'], category: 'event', usage: 'event <子指令>', description: '世界事件' },
  { id: 'auto', names: ['auto'], category: 'auto', usage: 'auto <子指令>', description: '自動戰鬥' },
  { id: 'tutorial', names: ['tutorial'], category: 'other', usage: 'tutorial [skip]', description: '教學系統' },
  { id: 'signin', names: ['signin', 'checkin'], category: 'other', usage: 'signin', description: '每日簽到' },
  { id: 'debug', names: ['debug'], category: 'other', usage: 'debug <子指令>', description: '除錯指令', hidden: true },
  { id: 'help', names: ['help'], category: 'other', usage: 'help [分類]', description: '查看指令說明' },
  { id: 'alias', names: ['alias'], category: 'other', usage: 'alias <名稱> <指令>', description: '設定指令別名' },
  { id: 'unalias', names: ['unalias'], category: 'other', usage: 'unalias <名稱>', description: '刪除指令別名' },
];
