import type { FaithDef, GenderDef, RaceDef } from '../types/origin.js';

export const RACE_DEFS: Record<string, RaceDef> = {
  human: {
    id: 'human',
    name: '人類',
    description: '適應力極強的年輕族群，能快速學會各地技藝。',
    statMods: {},
    passiveSkillId: 'race_human_adaptability',
    passiveName: '適應力',
    passiveDescription: '獲得經驗值 +3%，所有生活技能熟練度獲取 +3%。',
    tags: ['balanced', 'learning'],
  },
  elf: {
    id: 'elf',
    name: '精靈',
    description: '感官敏銳、親近自然與奧術，但身體較不耐重創。',
    statMods: { int: 2, dex: 1, vit: -1 },
    passiveSkillId: 'race_elf_keen_senses',
    passiveName: '靈敏感知',
    passiveDescription: '搜尋、陷阱察覺、自然場景探索成功率提高。',
    tags: ['arcane', 'nature', 'search'],
  },
  dwarf: {
    id: 'dwarf',
    name: '矮人',
    description: '石廳與熔爐孕育出的堅韌族群，擅長承受壓力與工藝。',
    statMods: { vit: 2, str: 1, dex: -1 },
    passiveSkillId: 'race_dwarf_stoneblood',
    passiveName: '石血體質',
    passiveDescription: '物理減傷 +2%，採礦與鍛造熟練度獲取 +5%。',
    tags: ['crafting', 'mining', 'sturdy'],
  },
  orc: {
    id: 'orc',
    name: '獸人',
    description: '戰血旺盛的部族後裔，擅長在負傷時爆發更強攻勢。',
    statMods: { str: 3, vit: 1, int: -1 },
    passiveSkillId: 'race_orc_battleblood',
    passiveName: '戰血',
    passiveDescription: '生命低於 35% 時，造成傷害 +5%。',
    tags: ['melee', 'risk'],
  },
  halfling: {
    id: 'halfling',
    name: '半身人',
    description: '腳步輕快、運氣極佳的旅者，總能避開最糟的麻煩。',
    statMods: { dex: 2, luk: 2, str: -1 },
    passiveSkillId: 'race_halfling_lucky_steps',
    passiveName: '幸運腳步',
    passiveDescription: '陷阱傷害降低，稀有掉落判定小幅提高，逃跑成功率 +5%。',
    tags: ['luck', 'mobility', 'loot'],
  },
  dragonborn: {
    id: 'dragonborn',
    name: '龍裔',
    description: '血脈中仍殘留古龍餘燼的族群，天生具有元素抗性。',
    statMods: { str: 1, vit: 1, int: 1, luk: -1 },
    passiveSkillId: 'race_dragonborn_dragonblood',
    passiveName: '龍血抗性',
    passiveDescription: '建立角色時選擇一個血脈元素，該元素承傷降低。',
    tags: ['elemental', 'hybrid'],
  },
  shadowkin: {
    id: 'shadowkin',
    name: '影裔',
    description: '受幽影界影響的血脈，擅長黑暗中的行動與禁忌力量。',
    statMods: { int: 2, luk: 1, vit: -1 },
    passiveSkillId: 'race_shadowkin_shadow_affinity',
    passiveName: '幽影親和',
    passiveDescription: '黑暗區域探索懲罰降低；暗屬性傷害 +3%，光屬性承傷 +3%。',
    tags: ['dark', 'exploration'],
  },
};

export const GENDER_DEFS: Record<string, GenderDef> = {
  male: { id: 'male', name: '男性', description: '只影響稱謂與敘事，不影響能力。' },
  female: { id: 'female', name: '女性', description: '只影響稱謂與敘事，不影響能力。' },
  nonbinary: { id: 'nonbinary', name: '非二元', description: '只影響稱謂與敘事，不影響能力。' },
  undisclosed: { id: 'undisclosed', name: '不透露', description: '只影響稱謂與敘事，不影響能力。' },
};

export const FAITH_DEFS: Record<string, FaithDef> = {
  aelora: {
    id: 'aelora',
    name: '艾洛拉',
    title: '黎明女神',
    domains: ['光明', '治療', '重生', '守護'],
    description: '守護晨光與重生的女神，接納尋求庇護與治療的人。',
    passiveSkillId: 'faith_aelora_dawn_grace',
    passiveName: '黎明恩澤',
    passiveDescription: '受到治療效果 +3%。每日第一次死亡懲罰降低少量。',
    prayerBlessingId: 'blessing_aelora_morning_guard',
    prayerName: '晨光庇護',
    prayerDescription: '短時間內 HP 自然恢復提高，暗屬性承傷降低。',
    taboos: ['惡意殺害中立 NPC', '頻繁掠奪弱者'],
    tags: ['light', 'healing', 'protection'],
  },
  karvos: {
    id: 'karvos',
    name: '卡爾沃',
    title: '戰爭之主',
    domains: ['戰鬥', '勇氣', '榮耀', '征服'],
    description: '鼓勵正面衝突與榮耀勝利的戰爭神。',
    passiveSkillId: 'faith_karvos_battle_fervor',
    passiveName: '戰意不息',
    passiveDescription: '進入戰鬥第一回合造成傷害 +3%。',
    prayerBlessingId: 'blessing_karvos_war_drums',
    prayerName: '戰鼓迴響',
    prayerDescription: '短時間內物理傷害提高，但逃跑成功率降低。',
    taboos: ['連續逃離戰鬥', '拒絕榮耀決鬥', '投降'],
    tags: ['war', 'damage'],
  },
  ithern: {
    id: 'ithern',
    name: '伊瑟恩',
    title: '知識神',
    domains: ['知識', '魔法', '記錄', '預言'],
    description: '庇護學者、法師與記錄者的神祗。',
    passiveSkillId: 'faith_ithern_whispering_pages',
    passiveName: '書頁低語',
    passiveDescription: '鑑定、古文、符文、機關解析成功率提高。',
    prayerBlessingId: 'blessing_ithern_clear_sight',
    prayerName: '明晰之眼',
    prayerDescription: '短時間內搜尋與 inspect 額外顯示線索，法術命中小幅提高。',
    taboos: ['摧毀書籍', '拒絕記錄重要發現', '濫用禁術'],
    tags: ['knowledge', 'magic', 'inspect'],
  },
  mirak: {
    id: 'mirak',
    name: '米拉克',
    title: '財富與旅途之神',
    domains: ['交易', '旅行', '契約', '幸運'],
    description: '照看商旅、契約與道路的神祗。',
    passiveSkillId: 'faith_mirak_golden_road',
    passiveName: '金路眷顧',
    passiveDescription: '商店買入價格 -2%，旅行費用 -5%。',
    prayerBlessingId: 'blessing_mirak_lucky_coin',
    prayerName: '幸運錢幣',
    prayerDescription: '短時間內掉落金幣略增，稀有掉落判定小幅提高。',
    taboos: ['違約', '詐騙神殿商人', '偷竊信徒財物'],
    tags: ['trade', 'travel', 'luck'],
  },
  virdan: {
    id: 'virdan',
    name: '薇爾丹',
    title: '森林母神',
    domains: ['自然', '野獸', '採集', '生命循環'],
    description: '守護森林、野獸與生命循環的古老母神。',
    passiveSkillId: 'faith_virdan_forest_stride',
    passiveName: '林間步伐',
    passiveDescription: '野外區域探索懲罰降低，採集熟練度 +3%。',
    prayerBlessingId: 'blessing_virdan_green_breath',
    prayerName: '綠息',
    prayerDescription: '短時間內採集額外產出機率提高，毒/自然傷害承受降低。',
    taboos: ['過度獵殺低等野獸', '破壞自然聖地'],
    tags: ['nature', 'gathering'],
  },
  shalan: {
    id: 'shalan',
    name: '莎蘭',
    title: '月影女神',
    domains: ['夜晚', '秘密', '夢境', '隱匿'],
    description: '庇護秘密、夢境與月下行者的女神。',
    passiveSkillId: 'faith_shalan_moon_whisper',
    passiveName: '月下低語',
    passiveDescription: '夜晚或黑暗房間中閃避 +2%，搜尋隱藏物成功率提高。',
    prayerBlessingId: 'blessing_shalan_dream_veil',
    prayerName: '夢紗',
    prayerDescription: '短時間內逃跑成功率提高，敵人第一擊命中率降低。',
    taboos: ['洩露秘密', '破壞誓言', '在神殿中說謊'],
    tags: ['stealth', 'night', 'secret'],
  },
  talorn: {
    id: 'talorn',
    name: '塔洛恩',
    title: '海潮與風暴之神',
    domains: ['海洋', '風暴', '航行', '雷電'],
    description: '掌管海潮、雷霆與航路誓言的風暴神。',
    passiveSkillId: 'faith_talorn_stormblood',
    passiveName: '風暴血脈',
    passiveDescription: '雷電與水系傷害承受 -3%。',
    prayerBlessingId: 'blessing_talorn_thunder_tide',
    prayerName: '雷潮之力',
    prayerDescription: '短時間內攻擊有小機率追加雷電傷害。',
    taboos: ['臨陣畏縮', '污染水源', '背棄航行誓言'],
    tags: ['storm', 'lightning', 'water'],
  },
  oser: {
    id: 'oser',
    name: '奧瑟',
    title: '冥河守門者',
    domains: ['死亡', '靈魂', '記憶', '亡者安息'],
    description: '守護冥河與亡者記憶的沉默神祗。',
    passiveSkillId: 'faith_oser_dead_whispers',
    passiveName: '亡者低語',
    passiveDescription: '與屍體、墓地、亡靈場景互動時更容易發現線索。',
    prayerBlessingId: 'blessing_oser_river_mark',
    prayerName: '冥河印記',
    prayerDescription: '短時間內死亡懲罰降低，暗屬性承受降低，但光屬性承受略升。',
    taboos: ['褻瀆亡者', '盜墓後不獻祭', '干擾靈魂安息'],
    tags: ['death', 'corpse', 'dark'],
  },
  brokk: {
    id: 'brokk',
    name: '布洛克',
    title: '鍛火神',
    domains: ['鍛造', '火焰', '工藝', '耐性'],
    description: '守護熔爐、礦石與工匠誓約的鍛火神。',
    passiveSkillId: 'faith_brokk_forgeheart',
    passiveName: '爐心耐性',
    passiveDescription: '火焰承受 -3%，鍛造熟練度 +5%。',
    prayerBlessingId: 'blessing_brokk_forgefire',
    prayerName: '鍛火祝聖',
    prayerDescription: '短時間內修理/鍛造成功率提高，武器耐久消耗降低。',
    taboos: ['浪費稀有礦石', '破壞誓約武器', '偷竊工匠作品'],
    tags: ['forge', 'fire', 'crafting'],
  },
  nesha: {
    id: 'nesha',
    name: '奈薩',
    title: '虛空之眼',
    domains: ['虛空', '禁忌', '混沌', '代價'],
    description: '凝視代價與禁忌真相的虛空神祗。',
    passiveSkillId: 'faith_nesha_forbidden_echo',
    passiveName: '禁識殘響',
    passiveDescription: '暗/虛空系技能效果 +3%，但受到治療效果 -2%。',
    prayerBlessingId: 'blessing_nesha_rift_gaze',
    prayerName: '裂隙凝視',
    prayerDescription: '短時間內傷害提高，但每次戰鬥開始損失少量 HP。',
    taboos: ['拒絕代價', '淨化虛空祭壇', '服從光明神殿'],
    tags: ['void', 'dark', 'risk'],
  },
};

export const DEFAULT_RACE_ID = 'human';
export const DEFAULT_GENDER_ID = 'undisclosed';
export const DEFAULT_FAITH_ID = 'aelora';
