import type { RawSkillDef } from './types.js';

export const DRUID_SKILL_DEFS: Record<string, RawSkillDef> = {
// ════════════════════════════════════════════
  //  冥行者 (Lv 20+) - 祭司系二轉・靈界通道
  // ════════════════════════════════════════════

  spirit_sense: { id: 'spirit_sense', name: '靈界感知', englishName: 'Spirit Sense', classId: 'druid', learnLevel: 20, type: 'passive', targetType: 'self', resourceCost: 0, cooldown: 0, damageType: 'pure', element: 'none', multiplier: 0, description: '冥行者的核心系統。可感知靈界——看到死去隊友的靈魂和隱藏的靈體敵人。可進入靈界（免疫物理、魔傷×1.5），在靈界中拉回死者靈魂復活，或推敵人進靈界放逐。', shortDescription: '可進入靈界（免疫物理、魔傷×1.5）。靈界中可復活死者、放逐敵人。', fullDescription: '被動。定義靈界系統：可看到靈界（死去隊友靈魂、隱藏靈體）。進入靈界後免疫物理攻擊、受魔法傷害×1.5。可拉回死者靈魂復活、推敵人進靈界暫時消失。', tags: ['passive', 'support'], special: { spiritWorldSystem: true, physicalImmune: true, magicVulnerability: 1.5 } },

spirit_crossing: { id: 'spirit_crossing', name: '靈界穿越', englishName: 'Spirit Crossing', classId: 'druid', learnLevel: 20, type: 'active', targetType: 'self', resourceCost: 20, cooldown: 5, damageType: 'pure', element: 'none', multiplier: 0, description: '穿越維度的壁壘進入靈界。靈界中免疫物理攻擊但受魔法傷害×1.5。可看到並互動死者靈魂。不能對物質世界目標施法。', shortDescription: '進入靈界。免疫物理、魔傷×1.5。可互動靈魂。不能對物質世界施法。', fullDescription: '消耗20信仰，冷卻5。進入靈界。免疫物理攻擊，魔法傷害×1.5。可看到死者靈魂並互動。不能對物質世界的目標施法。', tags: ['defense', 'support'], special: { enterSpiritWorld: true } },

soul_pull: { id: 'soul_pull', name: '靈魂牽引', englishName: 'Soul Pull', classId: 'druid', learnLevel: 20, type: 'active', targetType: 'single_ally', resourceCost: 30, cooldown: 8, damageType: 'pure', element: 'light', multiplier: 0, description: '在靈界中使用：拉回死去隊友的靈魂=復活（HP40%）。或將一個敵人推入靈界暫時消失3tick。', shortDescription: '靈界中：拉回死者靈魂=復活HP40%。或推敵人進靈界消失3tick。', fullDescription: '消耗30信仰，冷卻8。靈界限定。拉回死去隊友靈魂=復活（HP40%）。或推一個敵人進靈界（消失3tick，回來時受光傷）。', tags: ['heal', 'control', 'support', 'light'], special: { spiritWorldRequired: true, revive: true, reviveHpPercent: 40, banishDuration: 3 } },

spirit_return: { id: 'spirit_return', name: '靈界歸還', englishName: 'Spirit Return', classId: 'druid', learnLevel: 20, type: 'active', targetType: 'all_enemies', resourceCost: 10, cooldown: 3, damageType: 'magical', element: 'light', multiplier: 1.0, description: '從靈界回到物質世界。歸還瞬間靈界能量衝擊周圍敵人，造成光傷並使其陷入短暫恐懼。', shortDescription: '回到物質世界。衝擊周圍敵人：100%光傷+恐懼1tick。', fullDescription: '消耗10信仰，冷卻3。從靈界回到物質世界。歸還時對周圍敵人造成100%光屬性魔法傷害+恐懼1tick。', effects: [{ type: 'fear', value: 1, duration: 1 }], tags: ['damage', 'aoe', 'control', 'light'], special: { exitSpiritWorld: true } },

spirit_ward: { id: 'spirit_ward', name: '靈界守護', englishName: 'Spirit Ward', classId: 'druid', learnLevel: 25, type: 'passive', targetType: 'self', resourceCost: 0, cooldown: 0, damageType: 'pure', element: 'none', multiplier: 0, description: '對靈界的深入理解減輕了跨界的負擔。靈界中魔傷加倍從×1.5降至×1.2，穿越冷卻-2tick。', shortDescription: '靈界魔傷×1.5降至×1.2。穿越CD-2。', fullDescription: '被動。靈界中受魔法傷害倍率從×1.5降至×1.2。靈界穿越冷卻-2tick。', tags: ['passive', 'defense'], special: { magicVulnerability: 1.2 } },

cross_heal: { id: 'cross_heal', name: '跨界治療', englishName: 'Cross-world Heal', classId: 'druid', learnLevel: 29, type: 'active', targetType: 'single_ally', resourceCost: 20, cooldown: 4, damageType: 'pure', element: 'light', multiplier: 0, description: '突破靈界與物質世界的隔閡，在靈界中對物質世界的友方施放治療（效果-30%）。', shortDescription: '靈界中可治療物質世界友方（效果-30%）。', fullDescription: '消耗20信仰，冷卻4。靈界中使用。對物質世界友方治療20%最大HP（跨界減益30%=實際14%）。', tags: ['heal', 'support', 'light'], special: { spiritWorldRequired: true, isHeal: true, crossWorldPenalty: 0.3 } },

spirit_banish: { id: 'spirit_banish', name: '靈界放逐', englishName: 'Spirit Banish', classId: 'druid', learnLevel: 33, type: 'active', targetType: 'single_enemy', resourceCost: 25, cooldown: 6, damageType: 'magical', element: 'light', multiplier: 0.5, description: '不用進靈界。直接將一個敵人推入靈界3tick。敵人回來時受到光傷。', shortDescription: '直接推敵人進靈界3tick（不用自己進去）。回來時受光傷。', fullDescription: '消耗25信仰，冷卻6。不需要在靈界中。直接將一個敵人推入靈界消失3tick。敵人回來時受50%光傷。', tags: ['control', 'light'], special: { banishDuration: 3 } },

spirit_link: { id: 'spirit_link', name: '靈魂鏈接', englishName: 'Spirit Link', classId: 'druid', learnLevel: 37, type: 'active', targetType: 'single_ally', resourceCost: 20, cooldown: 6, damageType: 'pure', element: 'none', multiplier: 0, description: '在靈界中連結自己和一名友方。3tick共享HP，傷害平分，治療共享。', shortDescription: '靈界中：3tick與友方共享HP（傷害平分、治療共享）。', fullDescription: '消耗20信仰，冷卻6。靈界中使用。3tick內與一名友方共享HP池：傷害平分承受，治療雙方共享。', tags: ['defense', 'support'], special: { spiritWorldRequired: true, hpShare: true, duration: 3 } },

mass_revival: { id: 'mass_revival', name: '集體牽引', englishName: 'Mass Revival', classId: 'druid', learnLevel: 45, type: 'active', targetType: 'all_allies', resourceCost: 40, cooldown: 10, damageType: 'magical', element: 'light', multiplier: 1.5, description: '靈界中同時拉回所有死去隊友的靈魂。AoE復活+打斷周圍敵人+驅散護盾。', shortDescription: '靈界中：AoE復活所有死者HP30%。打斷+驅散周圍敵人。', fullDescription: '消耗40信仰，冷卻10。靈界限定。同時復活所有死去隊友（HP30%）+對周圍敵人150%光傷+打斷+驅散。', effects: [{ type: 'stun', value: 1, duration: 1 }], tags: ['heal', 'aoe', 'interrupt', 'light'], special: { castTime: 1, spiritWorldRequired: true, massRevive: true, interrupt: true, dispelShield: true } },

spirit_unity: { id: 'spirit_unity', name: '靈肉合一', englishName: 'Spirit Unity', classId: 'druid', learnLevel: 50, type: 'active', targetType: 'self', resourceCost: 40, cooldown: 12, damageType: 'pure', element: 'light', multiplier: 0, description: '終極奧義：8tick同時存在於物質世界和靈界。可對兩界目標施法，免疫物理，魔傷無加倍。', shortDescription: '8tick同時存在兩界。可對所有目標施法，免疫物理，魔傷無加倍。', fullDescription: '消耗40信仰，冷卻12。8tick同時存在於物質世界和靈界。可對兩界所有目標施法。免疫物理攻擊，魔法傷害不加倍。', tags: ['buff', 'burst', 'support'], special: { spiritUnity: true, duration: 8, physicalImmune: true, magicVulnerability: 1.0 } },
};
