import type { RawSkillDef } from './types.js';

export const HIGH_PRIEST_SKILL_DEFS: Record<string, RawSkillDef> = {
// ════════════════════════════════════════════
  //  神殿師 (Lv 20+) - 祭司系二轉・祭壇建造
  // ════════════════════════════════════════════

  temple_architecture: { id: 'temple_architecture', name: '聖殿建築', englishName: 'Temple Architecture', classId: 'high_priest', learnLevel: 20, type: 'passive', targetType: 'self', resourceCost: 0, cooldown: 0, damageType: 'pure', element: 'none', multiplier: 0, description: '神殿師的核心系統。可在房間中建造祭壇——一個有HP的實體結構。祭壇每tick自動治療房內所有友方。可升級祭壇強化效果，也可將敵人獻祭造成AoE傷害。', shortDescription: '可建造祭壇（有HP實體），每tick自動治療全隊。可升級，可獻祭敵人轉為AoE傷害。', fullDescription: '被動。定義祭壇系統：可建造有HP的祭壇結構。祭壇每tick治療房內全隊。可升級(Lv1-3)強化效果。可將敵人獻祭轉為AoE傷害（獻祭期間停止回血）。', tags: ['passive', 'summon', 'heal'], special: { altarSystem: true } },

build_altar: { id: 'build_altar', name: '建造祭壇', englishName: 'Build Altar', classId: 'high_priest', learnLevel: 20, type: 'active', targetType: 'self', resourceCost: 25, cooldown: 5, damageType: 'pure', element: 'light', multiplier: 0, description: '以信仰之力在房間中建造Lv1祭壇。祭壇有自身的HP，每tick自動治療本房所有友方3%HP。離開房間時祭壇留在原地。', shortDescription: '建造Lv1祭壇（HP=你50%）。每tick全隊回3%HP。離開房間祭壇留下。', fullDescription: '消耗25信仰，冷卻5。建造Lv1祭壇（HP=施法者50%）。祭壇每tick自動治療本房所有友方3%最大HP。離開房間祭壇留下，到新房間需重建。', tags: ['summon', 'heal', 'support', 'light'], special: { buildAltar: true, altarLevel: 1, altarHpRatio: 0.5, healPercent: 3 } },

upgrade_altar: { id: 'upgrade_altar', name: '祭壇升級', englishName: 'Upgrade Altar', classId: 'high_priest', learnLevel: 20, type: 'active', targetType: 'self', resourceCost: 20, cooldown: 3, damageType: 'pure', element: 'light', multiplier: 0, description: '消耗信仰升級現有祭壇。Lv2：回血5%+自動驅散debuff。Lv3：回血8%+驅散+阻止一次死亡。升級同時增加獻祭傷害。', shortDescription: 'Lv2（5%+驅散）/ Lv3（8%+驅散+擋死1次）。升級增加獻祭傷害。', fullDescription: '消耗20信仰/級，冷卻3。升級祭壇：Lv2（每tick回5%HP+自動驅散）/ Lv3（每tick回8%HP+驅散+擋死1次）。同時提升獻祭傷害倍率。', tags: ['support', 'heal', 'light'], special: { upgradeAltar: true } },

sacrifice_enemy: { id: 'sacrifice_enemy', name: '獻祭', englishName: 'Sacrifice', classId: 'high_priest', learnLevel: 20, type: 'active', targetType: 'single_enemy', resourceCost: 15, cooldown: 3, damageType: 'magical', element: 'light', multiplier: 1.0, description: '將一名敵人丟到祭壇上獻祭。3tick對房內所有敵人造成持續光傷。祭壇等級越高獻祭傷害越大。獻祭期間祭壇停止回血。', shortDescription: '丟敵人到祭壇。3tick AoE光傷（祭壇等級增幅）。獻祭期間停止回血。CD3。', fullDescription: '消耗15信仰，冷卻3。將敵人獻祭給祭壇。3tick對房內全體敵人造成100%光傷/tick（Lv2×1.5、Lv3×2）。獻祭期間祭壇停止治療。', tags: ['damage', 'aoe', 'light'], special: { altarSacrifice: true, duration: 3 } },

altar_fortify: { id: 'altar_fortify', name: '祭壇強化', englishName: 'Altar Fortify', classId: 'high_priest', learnLevel: 25, type: 'passive', targetType: 'self', resourceCost: 0, cooldown: 0, damageType: 'pure', element: 'none', multiplier: 0, description: '祭壇建造工藝的精進。祭壇HP提升至施法者80%，Lv1基礎回血從3%提升至4%。', shortDescription: '祭壇HP提升至80%，Lv1回血4%/tick。', fullDescription: '被動。祭壇HP上限從施法者50%提升至80%。Lv1祭壇回血從3%/tick提升至4%/tick。', tags: ['passive', 'buff'], special: { altarHpRatio: 0.8 } },

holy_burst: { id: 'holy_burst', name: '神聖爆發', englishName: 'Holy Burst', classId: 'high_priest', learnLevel: 29, type: 'active', targetType: 'all_allies', resourceCost: 30, cooldown: 8, damageType: 'pure', element: 'light', multiplier: 0, description: '消耗祭壇所有等級能量，對全隊釋放大量治療並驅散所有debuff。祭壇降回Lv1。', shortDescription: '消耗祭壇等級，全隊大量治療+驅散。祭壇降回Lv1。', fullDescription: '消耗30信仰，冷卻8。消耗祭壇所有升級等級：每消耗1級治療全隊15%HP+驅散所有debuff。祭壇降回Lv1。', tags: ['heal', 'support', 'light'], special: { isHeal: true, altarBurst: true } },

altar_link: { id: 'altar_link', name: '祭壇連結', englishName: 'Altar Link', classId: 'high_priest', learnLevel: 33, type: 'active', targetType: 'self', resourceCost: 10, cooldown: 6, damageType: 'pure', element: 'none', multiplier: 0, description: '在相鄰房間建造一座分壇，與主壇共存。分壇有Lv1效果。', shortDescription: '在相鄰房間建造分壇（Lv1效果），與主壇共存。', fullDescription: '消耗10信仰，冷卻6。在指定相鄰房間建造分壇（Lv1效果：3%回血/tick）。分壇與主壇獨立存在。', tags: ['summon', 'support'], special: { altarLink: true, crossRoom: true } },

divine_barrier: { id: 'divine_barrier', name: '神聖屏障', englishName: 'Divine Barrier', classId: 'high_priest', learnLevel: 37, type: 'active', targetType: 'all_allies', resourceCost: 25, cooldown: 6, damageType: 'pure', element: 'light', multiplier: 0, description: '祭壇釋放神聖屏障，全隊3tick減傷30%。屏障期間祭壇不回血。', shortDescription: '祭壇釋放屏障，3tick全隊減傷30%。期間不回血。', fullDescription: '消耗25信仰，冷卻6。祭壇釋放神聖屏障3tick：全隊減傷30%。屏障期間祭壇停止治療。', effects: [{ type: 'damage_reduction', value: 30, duration: 3 }], tags: ['defense', 'support', 'light'], special: { altarBarrier: true } },

enhanced_sacrifice: { id: 'enhanced_sacrifice', name: '獻祭強化', englishName: 'Enhanced Sacrifice', classId: 'high_priest', learnLevel: 45, type: 'active', targetType: 'all_enemies', resourceCost: 20, cooldown: 5, damageType: 'magical', element: 'light', multiplier: 1.5, description: '強化版獻祭：可同時將2名敵人丟上祭壇，傷害疊加。打斷施法+驅散護盾。', shortDescription: '獻祭2名敵人，傷害疊加。打斷+驅散。', fullDescription: '消耗20信仰，冷卻5。同時獻祭2名敵人到祭壇。AoE傷害疊加（150%×2）+打斷施法+驅散護盾。獻祭期間祭壇停止治療。', effects: [{ type: 'stun', value: 1, duration: 1 }], tags: ['damage', 'aoe', 'interrupt', 'light'], special: { altarSacrifice: true, dualSacrifice: true, interrupt: true, dispelShield: true } },

eternal_temple: { id: 'eternal_temple', name: '永恆聖殿', englishName: 'Eternal Temple', classId: 'high_priest', learnLevel: 50, type: 'active', targetType: 'self', resourceCost: 40, cooldown: 12, damageType: 'pure', element: 'light', multiplier: 0, description: '以全部信仰之力將祭壇昇華為永恆聖殿。8tick祭壇直接升至Lv3+，HP翻倍，回血和獻祭效果全部×1.5。', shortDescription: '8tick祭壇升至Lv3+，HP翻倍，所有效果×1.5。', fullDescription: '消耗40信仰，冷卻12。8tick內祭壇直接升至Lv3+：HP翻倍、回血效果×1.5（12%/tick）、獻祭傷害×1.5。8tick後祭壇回到原等級。', tags: ['buff', 'burst', 'support'], special: { eternalTemple: true, duration: 8 } },
};
