import type { RawSkillDef } from './types.js';

export const INQUISITOR_SKILL_DEFS: Record<string, RawSkillDef> = {
// ════════════════════════════════════════════
  //  裁決者 (Lv 20+) - 祭司系二轉・罪業系統
  // ════════════════════════════════════════════

  eye_of_sin: { id: 'eye_of_sin', name: '罪業之眼', englishName: 'Eye of Sin', classId: 'inquisitor', learnLevel: 20, type: 'passive', targetType: 'self', resourceCost: 0, cooldown: 0, damageType: 'pure', element: 'none', multiplier: 0, description: '裁決者的核心系統。所有敵人的行動自動累積罪業（0-10）：攻擊+1、施法+1、自我治療+2、增益自身+1。你可以看到每個敵人的罪業數。', shortDescription: '敵人行動自動累積罪業0-10（攻擊+1、施法+1、自療+2、增益+1）。', fullDescription: '被動。所有敵人的行動自動累積罪業（0-10）：攻擊+1罪、施法+1罪、自我治療+2罪、增益自身+1罪。裁決者可看到每個敵人的罪業計數。', tags: ['passive', 'debuff'], special: { sinSystem: true, sinGain: { attack: 1, cast: 1, selfHeal: 2, selfBuff: 1 }, maxSin: 10 } },

judgment_strike: { id: 'judgment_strike', name: '審判', englishName: 'Judgment', classId: 'inquisitor', learnLevel: 20, type: 'active', targetType: 'single_enemy', resourceCost: 15, cooldown: 3, damageType: 'magical', element: 'light', multiplier: 0.5, description: '消耗目標所有罪業，每點罪業轉化為50%光屬性魔法傷害。需要目標至少3點罪業才能施放。罪業越高，審判越致命。', shortDescription: '消耗所有罪業，每點=50%光傷。需3+罪。', fullDescription: '消耗15信仰，冷卻3。消耗目標所有罪業，每點罪業=50%光屬性魔法傷害。需3+罪業才能施放。', tags: ['damage', 'single_target', 'light'], special: { sinConsume: true, sinMinRequired: 3, damagePerSin: 50 } },

absolution: { id: 'absolution', name: '赦免', englishName: 'Absolution', classId: 'inquisitor', learnLevel: 20, type: 'active', targetType: 'single_enemy', resourceCost: 15, cooldown: 3, damageType: 'pure', element: 'light', multiplier: 0, description: '以慈悲之心赦免目標的罪業，將每點罪業轉化為全隊的治療。慈悲的收割方式。', shortDescription: '消耗所有罪業，每點=全隊3%HP治療。', fullDescription: '消耗15信仰，冷卻3。消耗目標所有罪業，每點罪業=全隊回復3%最大HP。', tags: ['heal', 'support', 'light'], special: { sinConsume: true, isHeal: true, healPerSin: 3 } },

sin_gaze: { id: 'sin_gaze', name: '罪業注視', englishName: 'Sin Gaze', classId: 'inquisitor', learnLevel: 20, type: 'active', targetType: 'single_enemy', resourceCost: 10, cooldown: 4, damageType: 'pure', element: 'none', multiplier: 0, description: '以審判之眼凝視目標，讓其行為產生的罪業加倍累積。加速抵達審判的時刻。', shortDescription: '標記敵人5tick，期間罪業累積翻倍。', fullDescription: '消耗10信仰，冷卻4。標記一個敵人5tick。期間該敵人行動產生的罪業翻倍。', tags: ['debuff', 'control'], special: { sinGaze: true, sinMultiplier: 2, duration: 5 } },

chain_judgment: { id: 'chain_judgment', name: '連鎖審判', englishName: 'Chain Judgment', classId: 'inquisitor', learnLevel: 25, type: 'passive', targetType: 'self', resourceCost: 0, cooldown: 0, damageType: 'pure', element: 'none', multiplier: 0, description: '審判擊殺目標時，死者剩餘的罪業溢出，50%轉移到相鄰敵人身上。', shortDescription: '審判擊殺時罪業溢出：50%轉移到其他敵人。', fullDescription: '被動。審判技能擊殺目標時，死者剩餘罪業×50%轉移到本房其他敵人。', tags: ['passive', 'damage'], special: { sinOverflow: 0.5 } },

condemn: { id: 'condemn', name: '宣判', englishName: 'Condemn', classId: 'inquisitor', learnLevel: 29, type: 'active', targetType: 'single_enemy', resourceCost: 20, cooldown: 5, damageType: 'pure', element: 'light', multiplier: 0, description: '對罪業深重者宣判懲罰。消耗5點罪業：沉默2tick+受傷增加20%。不清空全部罪業。', shortDescription: '需5+罪。消耗5罪：沉默2tick+受傷+20%。不清空全部。', fullDescription: '消耗20信仰，冷卻5。需目標5+罪業。消耗5點罪業：沉默2tick+受到傷害增加20%持續3tick。', effects: [{ type: 'silence', value: 1, duration: 2 }], tags: ['control', 'debuff', 'light'], special: { sinConsume: true, sinMinRequired: 5, sinCost: 5 } },

mass_gaze: { id: 'mass_gaze', name: '群體注視', englishName: 'Mass Gaze', classId: 'inquisitor', learnLevel: 33, type: 'active', targetType: 'all_enemies', resourceCost: 25, cooldown: 6, damageType: 'pure', element: 'none', multiplier: 0, description: '以審判之眼掃視全場，本房所有敵人的罪業累積翻倍3tick。', shortDescription: 'AoE版罪業注視。全體罪業累積翻倍3tick。', fullDescription: '消耗25信仰，冷卻6。本房所有敵人罪業累積翻倍3tick。', tags: ['debuff', 'aoe', 'control'], special: { sinGaze: true, sinMultiplier: 2, duration: 3, aoe: true } },

atonement: { id: 'atonement', name: '贖罪', englishName: 'Atonement', classId: 'inquisitor', learnLevel: 37, type: 'active', targetType: 'single_enemy', resourceCost: 0, cooldown: 5, damageType: 'pure', element: 'none', multiplier: 0, description: '讀取目標的罪業，每點罪業為你回復2%HP+5%信仰。不消耗罪業。自我續航技。', shortDescription: '每點罪業=你回復2%HP+5%信仰。不消耗罪業。', fullDescription: '消耗0信仰，冷卻5。讀取目標罪業，每點=你回復2%最大HP+5%信仰。不消耗目標的罪業。', tags: ['heal', 'resource', 'support', 'defense'], special: { sinRead: true, hpPerSin: 2, faithPerSin: 5 } },

divine_punishment: { id: 'divine_punishment', name: '天罰', englishName: 'Divine Punishment', classId: 'inquisitor', learnLevel: 45, type: 'active', targetType: 'single_enemy', resourceCost: 30, cooldown: 8, damageType: 'magical', element: 'light', multiplier: 5.0, description: '對罪業滿溢者降下天罰。需10罪。500%光傷+打斷+驅散。非Boss可直接斬殺。', shortDescription: '需10罪滿。500%光傷+打斷+驅散。非Boss斬殺。', fullDescription: '消耗30信仰，冷卻8。需10罪業。消耗所有罪業造成500%光傷+打斷施法+驅散護盾。非Boss目標可直接斬殺。', effects: [{ type: 'stun', value: 1, duration: 2 }], tags: ['damage', 'single_target', 'burst', 'interrupt', 'light'], special: { castTime: 1, sinConsume: true, sinMinRequired: 10, interrupt: true, dispelShield: true, executeNonBoss: true } },

final_judgment: { id: 'final_judgment', name: '末日審判', englishName: 'Final Judgment', classId: 'inquisitor', learnLevel: 50, type: 'active', targetType: 'all_enemies', resourceCost: 40, cooldown: 12, damageType: 'magical', element: 'light', multiplier: 1.0, description: '終極裁決。AoE消耗所有敵人的罪業，每點=100%光傷。全場清算，罪無可逃。', shortDescription: 'AoE消耗全體敵人罪業。每點罪=100%光傷。全場清算。', fullDescription: '消耗40信仰，冷卻12。對本房所有敵人消耗其全部罪業，每點罪業=100%光屬性魔法傷害。全場清算。', tags: ['damage', 'aoe', 'burst', 'light'], special: { castTime: 2, sinConsume: true, damagePerSin: 100, aoe: true } },
};
